const fs   = require('fs')
const path = require('path')

// Locally: parse .env.local manually (no dotenv dependency needed)
if (!process.env.VERCEL) {
  try {
    const raw = fs.readFileSync(path.join(__dirname, '.env.local'), 'utf8')
    raw.split('\n').forEach(line => {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) return
      const idx = trimmed.indexOf('=')
      if (idx === -1) return
      const key = trimmed.slice(0, idx).trim()
      const val = trimmed.slice(idx + 1).trim()
      if (!process.env[key]) process.env[key] = val
    })
  } catch {
    console.warn('Warning: .env.local not found — falling back to process.env')
  }
}

const url = process.env.SUPABASE_URL
const key = process.env.SUPABASE_KEY

if (!url || !key) {
  console.error('Error: SUPABASE_URL and SUPABASE_KEY must be set.')
  console.error('Copy .env.example to .env.local and fill in your values.')
  process.exit(1)
}

const content = `// Auto-generated by build.js — do not edit or commit
window.SUPABASE_URL = '${url}'
window.SUPABASE_KEY = '${key}'
`

fs.mkdirSync(path.join(__dirname, 'public'), { recursive: true })
fs.writeFileSync(path.join(__dirname, 'public', 'config.js'), content)
console.log('✓ public/config.js generated')
